**The Questions neeeded to be solved for analysis are following**
**1 - Standardise the mail_sent_date column values to YYYY-MM-DD standard date format**
**2 - In which Year maximum number of emails were sent to doctors?**
**3 - Write a query to get total fine paid per Office**
**4 - Write a query to get the highest total fine and lowest total fine paid per state**
**5 - Write a query to get the least 2 states that had to pay minimum 'online' fine**
**6 - Write a query to find the number of doctors that contributed to the state having highest 'cash' fine**
**7 - Get the top 5 average fine paid per state and category.**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df_fine = pd.read_csv('Fines paid  by doctors.csv')

In [4]:
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category  cash_fine   online_fine   
0    Professional Advising  $2,625.00          $-     
1        Expert-Led Forums  $1,000.00          $-     
2  Business Related Travel       $-         $448.00   
3                    Meals       $-         $119.00   
4    Professional Advising  $1,800.00          $-

In [5]:
df_email = pd.read_excel('Emails sent.xlsx')

In [6]:
df_email.head()

name_last name_first name_middle       mail_sent_date  \
0  ADELGLASS    JEFFREY          M.  2009-05-22 00:00:00   
1   ADKINSON         N.    FRANKLIN           2010-04-17   
2      ALLEN       MARK          S.           2012-01-26   
3  AMSTERDAM     DANIEL         NaN           2014.11.15   
4    AMSTUTZ     HARLAN          C.           2014.07.17   

                                         office  
0       Center for Drug Evaluation and Research  
1  Center for Biologics Evaluation and Research  
2    Center for Devices and Radiological Health  
3  Center for Biologics Evaluation and Research  
4    Center for Devices and Radiological Health

**Question - Standardise the mail_sent_date column values to YYYY-MM-DD standard date format**

In [7]:
df_email['mail_sent_date'] = pd.to_datetime(df_email['mail_sent_date'])
df_email.head()

name_last name_first name_middle mail_sent_date  \
0  ADELGLASS    JEFFREY          M.     2009-05-22   
1   ADKINSON         N.    FRANKLIN     2010-04-17   
2      ALLEN       MARK          S.     2012-01-26   
3  AMSTERDAM     DANIEL         NaN     2014-11-15   
4    AMSTUTZ     HARLAN          C.     2014-07-17   

                                         office  
0       Center for Drug Evaluation and Research  
1  Center for Biologics Evaluation and Research  
2    Center for Devices and Radiological Health  
3  Center for Biologics Evaluation and Research  
4    Center for Devices and Radiological Health

In [8]:
df_email['year'] = df_email['mail_sent_date'].dt.year
df_email.head()

name_last name_first name_middle mail_sent_date  \
0  ADELGLASS    JEFFREY          M.     2009-05-22   
1   ADKINSON         N.    FRANKLIN     2010-04-17   
2      ALLEN       MARK          S.     2012-01-26   
3  AMSTERDAM     DANIEL         NaN     2014-11-15   
4    AMSTUTZ     HARLAN          C.     2014-07-17   

                                         office  year  
0       Center for Drug Evaluation and Research  2009  
1  Center for Biologics Evaluation and Research  2010  
2    Center for Devices and Radiological Health  2012  
3  Center for Biologics Evaluation and Research  2014  
4    Center for Devices and Radiological Health  2014

**Question - In which Year maximum number of emails were sent to doctors?**

In [9]:
result = df_email.groupby('year')['year'].count()
result

year
2006     1
2007    15
2008     8
2009    14
2010    25
2011    20
2012    16
2013    21
2014    32
2015    31
2016    25
2017    11
2018    23
2019    25
2020     5
Name: year, dtype: int64

**In th year 2014 is the answer**

**Question - Write a query to get total fine paid per Office**

In [10]:
df_fine[' cash_fine '] = df_fine[' cash_fine '].str.replace('$','')

<ipython-input-10-884530fbd3b8>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df_fine[' cash_fine '] = df_fine[' cash_fine '].str.replace('$','')


In [11]:
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category  cash_fine   online_fine   
0    Professional Advising   2,625.00          $-     
1        Expert-Led Forums   1,000.00          $-     
2  Business Related Travel        -         $448.00   
3                    Meals        -         $119.00   
4    Professional Advising   1,800.00          $-

In [12]:
df_fine[' online_fine '] = df_fine[' online_fine '].str.replace('$','')

<ipython-input-12-46756c9a1707>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df_fine[' online_fine '] = df_fine[' online_fine '].str.replace('$','')


In [13]:
df_fine[' cash_fine '].isnull().any()

False

In [14]:
df_fine[' online_fine '].isnull().any()

False

In [15]:
df_fine[' online_fine '] = df_fine[' online_fine '].str.replace(',','')
df_fine[' cash_fine '] = df_fine[' cash_fine '].str.replace(',','')
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category  cash_fine   online_fine   
0    Professional Advising    2625.00           -     
1        Expert-Led Forums    1000.00           -     
2  Business Related Travel        -          448.00   
3                    Meals        -          119.00   
4    Professional Advising    1800.00           -

In [16]:
df_fine[' online_fine '] = df_fine[' online_fine '].str.replace('-','0')
df_fine[' cash_fine '] = df_fine[' cash_fine '].str.replace('-','0')
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category  cash_fine   online_fine   
0    Professional Advising    2625.00           0     
1        Expert-Led Forums    1000.00           0     
2  Business Related Travel        0          448.00   
3                    Meals        0          119.00   
4    Professional Advising    1800.00           0

In [17]:
df_fine[' cash_fine '].isnull().values.any()

False

In [18]:
df_fine[' cash_fine '] = df_fine[' cash_fine '].astype(str)

In [19]:
df_fine[' cash_fine '].dtype

dtype('O')

In [20]:
df_fine.to_csv('test.csv')

In [21]:
df_fine[' cash_fine '].isnull().any()

False

In [22]:
np.where(df_fine[' cash_fine '].isnull())[0]

array([], dtype=int64)

In [23]:
df_fine.dropna()

org_indiv first_name    last_name         city state  \
0      3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1              AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2        ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3        ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4        ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
...                         ...        ...          ...          ...   ...   
10082    ZUWALLACK, RICHARD LEO    RICHARD    ZUWALLACK     HARTFORD    CT   
10083    ZUWALLACK, RICHARD LEO    RICHARD    ZUWALLACK     HARTFORD    CT   
10084           ZUZARTE, EDWARD     EDWARD      ZUZARTE     ROSEDALE    MD   
10085           ZUZARTE, EDWARD     EDWARD      ZUZARTE     ROSEDALE    MD   
10086           ZUZARTE, EDWARD     EDWARD      ZUZARTE     ROSEDALE    MD   

                      category  cash_fine   online_fine   
0        Professional Advising    2625.00           0     
1            Expert-Led Forums    1000.00           0     
2      Business Related Travel        0          448.00   
3                        Meals        0          119.00   
4        Professional Advising    1800.00           0     
...                        ...         ...           ...  
10082        Expert-Led Forums    1750.00           0     
10083                    Meals        0           65.00   
10084  Business Related Travel        0           61.00   
10085        Expert-Led Forums    2000.00           0     
10086                    Meals        0           28.00   

[9883 rows x 8 columns]

In [24]:
df_fine[' online_fine '] = df_fine[' online_fine '].str.replace(' NA ','0')
df_fine[' cash_fine '] = df_fine[' cash_fine '].str.replace(' NA ','0')

In [25]:
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category  cash_fine   online_fine   
0    Professional Advising    2625.00           0     
1        Expert-Led Forums    1000.00           0     
2  Business Related Travel        0          448.00   
3                    Meals        0          119.00   
4    Professional Advising    1800.00           0

In [26]:
df_fine[' cash_fine '] = df_fine[' cash_fine '].astype(float)

In [27]:
df_fine[' online_fine '] = df_fine[' online_fine '].astype(float)

In [28]:
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category   cash_fine    online_fine   
0    Professional Advising       2625.0            0.0  
1        Expert-Led Forums       1000.0            0.0  
2  Business Related Travel          0.0          448.0  
3                    Meals          0.0          119.0  
4    Professional Advising       1800.0            0.0

In [29]:
df_fine['Total_fine'] = (df_fine[' cash_fine '] + df_fine[' online_fine '])
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category   cash_fine    online_fine   Total_fine  
0    Professional Advising       2625.0            0.0      2625.0  
1        Expert-Led Forums       1000.0            0.0      1000.0  
2  Business Related Travel          0.0          448.0       448.0  
3                    Meals          0.0          119.0       119.0  
4    Professional Advising       1800.0            0.0      1800.0

In [30]:
df_fine.to_csv('test1.csv')

In [31]:
output = df_fine.groupby('category').sum()['Total_fine']

In [32]:
output.sort_values(ascending=False)

category
Infosys Sponsored Research initiated before July 1, 2009         11137574.0
Expert-Led Forums                                                 9643970.0
Professional Advising                                             7569631.0
Infosys Sponsored Research initiated on or after July 1, 2009     2896911.0
Business Related Travel                                           1695329.0
Investigator-Initiated Research                                   1441855.0
Meals                                                              979419.0
Educational Items                                                   12322.0
Name: Total_fine, dtype: float64

**The above code ouput shows total fine paid by each office category**

**Question - Write a query to get the highest total fine and lowest total fine paid per state**

In [33]:
output2 = df_fine.groupby('state').sum()['Total_fine']
output2.sort_values(ascending=False)

state
CA    4737807.0
TX    2802196.0
FL    2564047.0
PA    2484505.0
NC    2328435.0
NY    2065042.0
MA    1764771.0
IL    1256825.0
MI    1146285.0
OH    1019450.0
MO     973586.0
CO     915238.0
MD     870905.0
TN     849225.0
AL     681699.0
AZ     641851.0
CT     632282.0
GA     618645.0
NJ     600842.0
MN     574800.0
WI     510122.0
KY     436938.0
SC     421491.0
WA     396066.0
UT     380892.0
VA     367992.0
IN     350339.0
KS     307205.0
OR     303740.0
LA     261921.0
DC     250541.0
IA     243706.0
RI     210204.0
NE     200250.0
NH     172369.0
AR     160932.0
PR     130394.0
WV     128372.0
OK     111523.0
MS      85276.0
NV      73024.0
NM      63830.0
DE      53987.0
HI      42617.0
WY      39962.0
ID      37656.0
VT      29888.0
SD      29503.0
ME      18731.0
ND      16146.0
MT      11208.0
AK       1750.0
Name: Total_fine, dtype: float64

**The Highest total fine payed by state is CA  - 4737807.0**

In [34]:
output2.sort_values()

state
AK       1750.0
MT      11208.0
ND      16146.0
ME      18731.0
SD      29503.0
VT      29888.0
ID      37656.0
WY      39962.0
HI      42617.0
DE      53987.0
NM      63830.0
NV      73024.0
MS      85276.0
OK     111523.0
WV     128372.0
PR     130394.0
AR     160932.0
NH     172369.0
NE     200250.0
RI     210204.0
IA     243706.0
DC     250541.0
LA     261921.0
OR     303740.0
KS     307205.0
IN     350339.0
VA     367992.0
UT     380892.0
WA     396066.0
SC     421491.0
KY     436938.0
WI     510122.0
MN     574800.0
NJ     600842.0
GA     618645.0
CT     632282.0
AZ     641851.0
AL     681699.0
TN     849225.0
MD     870905.0
CO     915238.0
MO     973586.0
OH    1019450.0
MI    1146285.0
IL    1256825.0
MA    1764771.0
NY    2065042.0
NC    2328435.0
PA    2484505.0
FL    2564047.0
TX    2802196.0
CA    4737807.0
Name: Total_fine, dtype: float64

**The Lowest total fine payed by state is AK - 1750.0**

**Question - Write a query to get the least 2 states that had to pay minimum 'online' fine**

In [35]:
output3 = df_fine.groupby('state').sum()[' online_fine ']
output3.sort_values().tail(2)

state
NY    224630.0
CA    406290.0
Name:  online_fine , dtype: float64

**The above code output is the answer**

**Question - Write a query to find the number of doctors that contributed to the state having highest 'cash' fine**

In [36]:
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category   cash_fine    online_fine   Total_fine  
0    Professional Advising       2625.0            0.0      2625.0  
1        Expert-Led Forums       1000.0            0.0      1000.0  
2  Business Related Travel          0.0          448.0       448.0  
3                    Meals          0.0          119.0       119.0  
4    Professional Advising       1800.0            0.0      1800.0

In [37]:
df_fine['first_name'] = df_fine['first_name'].astype(str)
df_fine['last_name'] = df_fine['last_name'].astype(str)
df_fine['full_name'] = df_fine['first_name'] + ' ' + df_fine['last_name']
df_fine.head()

org_indiv first_name    last_name         city state  \
0  3-D MEDICAL SERVICES LLC     STEVEN  DEITELZWEIG  NEW ORLEANS    LA   
1          AA DOCTORS, INC.     AAKASH        AHUJA  PASO ROBLES    CA   
2    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
3    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   
4    ABBO, LILIAN MARGARITA     LILIAN         ABBO        MIAMI    FL   

                  category   cash_fine    online_fine   Total_fine  \
0    Professional Advising       2625.0            0.0      2625.0   
1        Expert-Led Forums       1000.0            0.0      1000.0   
2  Business Related Travel          0.0          448.0       448.0   
3                    Meals          0.0          119.0       119.0   
4    Professional Advising       1800.0            0.0      1800.0   

            full_name  
0  STEVEN DEITELZWEIG  
1        AAKASH AHUJA  
2         LILIAN ABBO  
3         LILIAN ABBO  
4         LILIAN ABBO

In [38]:
output4 = df_fine.groupby('state')[' cash_fine '].agg(['sum','count'])
output4.sort_values('count',ascending=False)

sum  count
state                  
CA     4331517.0   1172
NY     1840412.0    833
FL     2400881.0    738
TX     2587047.0    624
PA     2376131.0    533
OH      895280.0    462
IL     1165328.0    448
NJ      539084.0    384
NC     2229157.0    383
MI     1068920.0    342
TN      782681.0    281
MA     1605375.0    259
GA      553320.0    248
MO      920765.0    237
MD      819911.0    196
IN      305220.0    196
VA      328365.0    177
WI      464600.0    169
CT      602323.0    155
AZ      613168.0    154
SC      395600.0    149
CO      884454.0    148
LA      228064.0    145
AL      641928.0    132
KY      402919.0    128
MN      527479.0    124
WA      352829.0    116
KS      282666.0     99
PR      113164.0     88
UT      354827.0     84
OK      103790.0     82
AR      153131.0     77
MS       74250.0     76
WV      106103.0     71
IA      231932.0     63
DC      211669.0     59
RI      187510.0     59
OR      286812.0     58
NV       66325.0     56
NE      191862.0     46
DE       49547.0     35
HI       33447.0     29
NH      158720.0     27
WY       36625.0     25
NM       59875.0     25
SD       23900.0     23
ID       32975.0     22
ME       15725.0     20
VT       26653.0     10
ND       15825.0     10
MT        8100.0      9
AK        1750.0      1

**The first value of the above code output is the answer**

**Question- Get the top 5 average fine paid per state and category**

In [39]:
output5 = df_fine.groupby('state').mean()['Total_fine']
output5.sort_values(ascending=False).head(5)

state
MA    6813.787645
NH    6384.037037
CO    6184.040541
NC    6079.464752
OR    5236.896552
Name: Total_fine, dtype: float64

**The above output of the code is for per state**

In [40]:
output5 = df_fine.groupby('category').mean()['Total_fine']
output5.sort_values(ascending=False).head(5)

category
Infosys Sponsored Research initiated on or after July 1, 2009    65838.886364
Infosys Sponsored Research initiated before July 1, 2009         54864.896552
Investigator-Initiated Research                                  42407.500000
Professional Advising                                             4963.692459
Expert-Led Forums                                                 3375.558278
Name: Total_fine, dtype: float64

**The above output of the code is per category**